const data ={
products :[
{_id :'1',
name :'Housse de chemise',
category: 'housse',
image:'/images/p1.png',
price:20,
brand:'unknown',
rating:4.5,
numReviews:10,
description:'housse de chemise classe aide à garder vos chemise propre et sans plis',
},
{_id :'2',
name :'Sac grande capacité',
category: 'sac',
image:'/images/p2.png',
price:30,
brand:'unknown',
rating:4.0,
numReviews:15,
description:'Sac grande capacité aide à garder vos affaires',
},
{_id :'3',
name :'Housse de chemise',
category: 'housse',
image:'/images/p3.png',
price:20,
brand:'unknown',
rating:4.5,
numReviews:10,
description:'housse de chemise classe aide à garder vos chemise propre et sans plis',
},
{_id :'4',
name :'sac ',
category: 'sac',
image:'/images/p4.png',
price:20,
brand:'unknown',
rating:4.5,
numReviews:10,
description:'housse de chemise classe aide à garder vos chemise propre et sans plis',
},
{_id :'5',
name :'Housse de chemise2',
category: 'housse',
image:'/images/p1.png',
price:20,
brand:'unknown',
rating:45,
numReviews:100,
description:'housse de chemise classe aide à garder vos chemise propre et sans plis',
},
{_id :'6',
name :'Housse de chemise3',
category: 'housse',
image:'/images/p1.png',
price:20,
brand:'unknown',
rating:4.5,
numReviews:10,
description:'housse de chemise classe aide à garder vos chemise propre et sans plis',
},
],
};
export default data;